name: Securelog Scan

on:
  workflow_call:
    inputs:
      exclude:
        description: "Comma-separated list of folders to exclude from scanning"
        required: false
        type: string
      commits:
        description: "Number of recent commits to scan"
        required: false
        type: number
      config:
        description: "Path to secure log scan config file"
        required: false
        type: string
      changed:
        description: "Scan only changed files"
        required: false
        type: boolean

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reusable workflow repository
        uses: actions/checkout@v3
        with:
          repository: Onboardbase/securelog-scan
          path: securelog-cli

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify the Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./securelog-cli

      - name: Run secret scan
        run: |
          CLI_COMMAND="node securelog-cli/bin/sls.js"
          if [ ! -z "${{ inputs.exclude }}" ]; then CLI_COMMAND="$CLI_COMMAND --exclude ${{ inputs.exclude }}"; fi
          if [ ! -z "${{ inputs.commits }}" ]; then CLI_COMMAND="$CLI_COMMAND --commits ${{ inputs.commits }}"; fi
          if [ ! -z "${{ inputs.config }}" ]; then CLI_COMMAND="$CLI_COMMAND --config ${{ inputs.config }}"; fi
          if [ "${{ inputs.changed }}" == "true" ]; then CLI_COMMAND="$CLI_COMMAND --changed"; fi
          eval "$CLI_COMMAND"
        working-directory: ./securelog-cli
