name: Securelog Scan

on:
  workflow_call:
    inputs:
      exclude:
        description: "Comma-separated list of folders to exclude from scanning"
        required: false
        type: string
      commits:
        description: "Number of recent commits to scan"
        required: false
        type: number
      config:
        description: "Path to secure log scan config file"
        required: false
        type: string
      changed:
        description: "Scan only changed files"
        required: false
        type: boolean
jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies for CLI
        working-directory: ./securelog-cli
        run: npm install

      - name: Run secret scan
        working-directory: ${{ github.workspace }}
        run: |
          CLI_COMMAND="node /bin/sls.js"

          # Append --exclude option if provided
          if [ -n "${{ inputs.exclude }}" ]; then
            CLI_COMMAND="$CLI_COMMAND --exclude ${{ inputs.exclude }}"
          fi

          # Append --commits option if provided
          if [ -n "${{ inputs.commits }}" ]; then
            CLI_COMMAND="$CLI_COMMAND --commits ${{ inputs.commits }}"
          fi

          # Append --config option if provided
          if [ -n "${{ inputs.config }}" ]; then
            CLI_COMMAND="$CLI_COMMAND --config ${{ inputs.config }}"
          fi

          # Append --changed option if true
          if [ "${{ inputs.changed }}" = "true" ]; then
            CLI_COMMAND="$CLI_COMMAND --changed"
          fi

          # Debug output to verify the final command
          echo "Running command: $CLI_COMMAND"

          # Execute the command
          eval "$CLI_COMMAND"
        shell: /usr/bin/bash -e {0}
